[package]
name = "greplog"
version = "0.1.0"
edition = "2021"
description = "Greplog observability SDK — Rust"

[dependencies]
greplog-core = { path = "../greplog-core" }
ulid = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry"] }
prost = "0.13"
bytes = "1"
axum = "0.7"
tower = { version = "0.4", features = ["util"] }
http = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
reqwest = "0.12"
