// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: greplog/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpanKind int32

const (
	SpanKind_SPAN_KIND_UNSPECIFIED SpanKind = 0
	SpanKind_SPAN_KIND_INTERNAL    SpanKind = 1
	SpanKind_SPAN_KIND_SERVER      SpanKind = 2
	SpanKind_SPAN_KIND_CLIENT      SpanKind = 3
	SpanKind_SPAN_KIND_PRODUCER    SpanKind = 4
	SpanKind_SPAN_KIND_CONSUMER    SpanKind = 5
)

// Enum value maps for SpanKind.
var (
	SpanKind_name = map[int32]string{
		0: "SPAN_KIND_UNSPECIFIED",
		1: "SPAN_KIND_INTERNAL",
		2: "SPAN_KIND_SERVER",
		3: "SPAN_KIND_CLIENT",
		4: "SPAN_KIND_PRODUCER",
		5: "SPAN_KIND_CONSUMER",
	}
	SpanKind_value = map[string]int32{
		"SPAN_KIND_UNSPECIFIED": 0,
		"SPAN_KIND_INTERNAL":    1,
		"SPAN_KIND_SERVER":      2,
		"SPAN_KIND_CLIENT":      3,
		"SPAN_KIND_PRODUCER":    4,
		"SPAN_KIND_CONSUMER":    5,
	}
)

func (x SpanKind) Enum() *SpanKind {
	p := new(SpanKind)
	*p = x
	return p
}

func (x SpanKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpanKind) Descriptor() protoreflect.EnumDescriptor {
	return file_greplog_v1_events_proto_enumTypes[0].Descriptor()
}

func (SpanKind) Type() protoreflect.EnumType {
	return &file_greplog_v1_events_proto_enumTypes[0]
}

func (x SpanKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpanKind.Descriptor instead.
func (SpanKind) EnumDescriptor() ([]byte, []int) {
	return file_greplog_v1_events_proto_rawDescGZIP(), []int{0}
}

type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED MetricType = 0
	MetricType_METRIC_TYPE_COUNTER     MetricType = 1
	MetricType_METRIC_TYPE_GAUGE       MetricType = 2
	MetricType_METRIC_TYPE_HISTOGRAM   MetricType = 3
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_UNSPECIFIED",
		1: "METRIC_TYPE_COUNTER",
		2: "METRIC_TYPE_GAUGE",
		3: "METRIC_TYPE_HISTOGRAM",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED": 0,
		"METRIC_TYPE_COUNTER":     1,
		"METRIC_TYPE_GAUGE":       2,
		"METRIC_TYPE_HISTOGRAM":   3,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_greplog_v1_events_proto_enumTypes[1].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_greplog_v1_events_proto_enumTypes[1]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_greplog_v1_events_proto_rawDescGZIP(), []int{1}
}

type LogEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceName      string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Level            string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`                                 // trace | debug | info | warn | error | fatal
	TimestampNs      int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // Unix epoch in nanoseconds
	LoggerName       string                 `protobuf:"bytes,5,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	File             string                 `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	Line             int32                  `protobuf:"varint,7,opt,name=line,proto3" json:"line,omitempty"`
	CorrelationId    string                 `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // optional pseudo-tracing link
	Attributes       map[string]string      `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StackTrace       []string               `protobuf:"bytes,10,rep,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	ExceptionType    string                 `protobuf:"bytes,11,opt,name=exception_type,json=exceptionType,proto3" json:"exception_type,omitempty"`
	ExceptionMessage string                 `protobuf:"bytes,12,opt,name=exception_message,json=exceptionMessage,proto3" json:"exception_message,omitempty"`
	EventId          string                 `protobuf:"bytes,13,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // client-supplied stable ID; content-hash fallback if empty
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_greplog_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_greplog_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_greplog_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *LogEvent) GetLoggerName() string {
	if x != nil {
		return x.LoggerName
	}
	return ""
}

func (x *LogEvent) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LogEvent) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LogEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *LogEvent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LogEvent) GetStackTrace() []string {
	if x != nil {
		return x.StackTrace
	}
	return nil
}

func (x *LogEvent) GetExceptionType() string {
	if x != nil {
		return x.ExceptionType
	}
	return ""
}

func (x *LogEvent) GetExceptionMessage() string {
	if x != nil {
		return x.ExceptionMessage
	}
	return ""
}

func (x *LogEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type Span struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceName         string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // e.g. "GET /api/users"
	StartTimeNs         int64                  `protobuf:"varint,3,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"`
	EndTimeNs           int64                  `protobuf:"varint,4,opt,name=end_time_ns,json=endTimeNs,proto3" json:"end_time_ns,omitempty"`
	CorrelationId       string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ParentCorrelationId string                 `protobuf:"bytes,6,opt,name=parent_correlation_id,json=parentCorrelationId,proto3" json:"parent_correlation_id,omitempty"`
	Route               string                 `protobuf:"bytes,7,opt,name=route,proto3" json:"route,omitempty"`
	Method              string                 `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"` // HTTP method or RPC name
	StatusCode          int32                  `protobuf:"varint,9,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error               string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Attributes          map[string]string      `protobuf:"bytes,11,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Kind                SpanKind               `protobuf:"varint,12,opt,name=kind,proto3,enum=greplog.v1.SpanKind" json:"kind,omitempty"`
	EventId             string                 `protobuf:"bytes,13,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // client-supplied stable ID; content-hash fallback if empty
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_greplog_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_greplog_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_greplog_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Span) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetStartTimeNs() int64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

func (x *Span) GetEndTimeNs() int64 {
	if x != nil {
		return x.EndTimeNs
	}
	return 0
}

func (x *Span) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Span) GetParentCorrelationId() string {
	if x != nil {
		return x.ParentCorrelationId
	}
	return ""
}

func (x *Span) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Span) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Span) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Span) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Span) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Span) GetKind() SpanKind {
	if x != nil {
		return x.Kind
	}
	return SpanKind_SPAN_KIND_UNSPECIFIED
}

func (x *Span) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // e.g. "http.request.duration"
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type          MetricType             `protobuf:"varint,6,opt,name=type,proto3,enum=greplog.v1.MetricType" json:"type,omitempty"`
	BucketValues  []float64              `protobuf:"fixed64,7,rep,packed,name=bucket_values,json=bucketValues,proto3" json:"bucket_values,omitempty"` // histogram buckets
	EventId       string                 `protobuf:"bytes,8,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                         // client-supplied stable ID; content-hash fallback if empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_greplog_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_greplog_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_greplog_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *Metric) GetBucketValues() []float64 {
	if x != nil {
		return x.BucketValues
	}
	return nil
}

func (x *Metric) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type IngestBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	BatchSeq      int64                  `protobuf:"varint,3,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"` // monotonically increasing per instance
	Logs          []*LogEvent            `protobuf:"bytes,10,rep,name=logs,proto3" json:"logs,omitempty"`
	Spans         []*Span                `protobuf:"bytes,11,rep,name=spans,proto3" json:"spans,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,12,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatch) Reset() {
	*x = IngestBatch{}
	mi := &file_greplog_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatch) ProtoMessage() {}

func (x *IngestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_greplog_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatch.ProtoReflect.Descriptor instead.
func (*IngestBatch) Descriptor() ([]byte, []int) {
	return file_greplog_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *IngestBatch) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *IngestBatch) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *IngestBatch) GetBatchSeq() int64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

func (x *IngestBatch) GetLogs() []*LogEvent {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *IngestBatch) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *IngestBatch) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	EventsCount   int64                  `protobuf:"varint,2,opt,name=events_count,json=eventsCount,proto3" json:"events_count,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_greplog_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greplog_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_greplog_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *IngestResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestResponse) GetEventsCount() int64 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

func (x *IngestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_greplog_v1_events_proto protoreflect.FileDescriptor

const file_greplog_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x17greplog/v1/events.proto\x12\n" +
	"greplog.v1\"\x85\x04\n" +
	"\bLogEvent\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03R\vtimestampNs\x12\x1f\n" +
	"\vlogger_name\x18\x05 \x01(\tR\n" +
	"loggerName\x12\x12\n" +
	"\x04file\x18\x06 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\a \x01(\x05R\x04line\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12D\n" +
	"\n" +
	"attributes\x18\t \x03(\v2$.greplog.v1.LogEvent.AttributesEntryR\n" +
	"attributes\x12\x1f\n" +
	"\vstack_trace\x18\n" +
	" \x03(\tR\n" +
	"stackTrace\x12%\n" +
	"\x0eexception_type\x18\v \x01(\tR\rexceptionType\x12+\n" +
	"\x11exception_message\x18\f \x01(\tR\x10exceptionMessage\x12\x19\n" +
	"\bevent_id\x18\r \x01(\tR\aeventId\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x04\n" +
	"\x04Span\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rstart_time_ns\x18\x03 \x01(\x03R\vstartTimeNs\x12\x1e\n" +
	"\vend_time_ns\x18\x04 \x01(\x03R\tendTimeNs\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x122\n" +
	"\x15parent_correlation_id\x18\x06 \x01(\tR\x13parentCorrelationId\x12\x14\n" +
	"\x05route\x18\a \x01(\tR\x05route\x12\x16\n" +
	"\x06method\x18\b \x01(\tR\x06method\x12\x1f\n" +
	"\vstatus_code\x18\t \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12@\n" +
	"\n" +
	"attributes\x18\v \x03(\v2 .greplog.v1.Span.AttributesEntryR\n" +
	"attributes\x12(\n" +
	"\x04kind\x18\f \x01(\x0e2\x14.greplog.v1.SpanKindR\x04kind\x12\x19\n" +
	"\bevent_id\x18\r \x01(\tR\aeventId\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x02\n" +
	"\x06Metric\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03R\vtimestampNs\x126\n" +
	"\x06labels\x18\x05 \x03(\v2\x1e.greplog.v1.Metric.LabelsEntryR\x06labels\x12*\n" +
	"\x04type\x18\x06 \x01(\x0e2\x16.greplog.v1.MetricTypeR\x04type\x12#\n" +
	"\rbucket_values\x18\a \x03(\x01R\fbucketValues\x12\x19\n" +
	"\bevent_id\x18\b \x01(\tR\aeventId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x01\n" +
	"\vIngestBatch\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tbatch_seq\x18\x03 \x01(\x03R\bbatchSeq\x12(\n" +
	"\x04logs\x18\n" +
	" \x03(\v2\x14.greplog.v1.LogEventR\x04logs\x12&\n" +
	"\x05spans\x18\v \x03(\v2\x10.greplog.v1.SpanR\x05spans\x12,\n" +
	"\ametrics\x18\f \x03(\v2\x12.greplog.v1.MetricR\ametrics\"e\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12!\n" +
	"\fevents_count\x18\x02 \x01(\x03R\veventsCount\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\x99\x01\n" +
	"\bSpanKind\x12\x19\n" +
	"\x15SPAN_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SPAN_KIND_INTERNAL\x10\x01\x12\x14\n" +
	"\x10SPAN_KIND_SERVER\x10\x02\x12\x14\n" +
	"\x10SPAN_KIND_CLIENT\x10\x03\x12\x16\n" +
	"\x12SPAN_KIND_PRODUCER\x10\x04\x12\x16\n" +
	"\x12SPAN_KIND_CONSUMER\x10\x05*t\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13METRIC_TYPE_COUNTER\x10\x01\x12\x15\n" +
	"\x11METRIC_TYPE_GAUGE\x10\x02\x12\x19\n" +
	"\x15METRIC_TYPE_HISTOGRAM\x10\x03B'Z%github.com/greplog/greplog-go/core/v1b\x06proto3"

var (
	file_greplog_v1_events_proto_rawDescOnce sync.Once
	file_greplog_v1_events_proto_rawDescData []byte
)

func file_greplog_v1_events_proto_rawDescGZIP() []byte {
	file_greplog_v1_events_proto_rawDescOnce.Do(func() {
		file_greplog_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greplog_v1_events_proto_rawDesc), len(file_greplog_v1_events_proto_rawDesc)))
	})
	return file_greplog_v1_events_proto_rawDescData
}

var file_greplog_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_greplog_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_greplog_v1_events_proto_goTypes = []any{
	(SpanKind)(0),          // 0: greplog.v1.SpanKind
	(MetricType)(0),        // 1: greplog.v1.MetricType
	(*LogEvent)(nil),       // 2: greplog.v1.LogEvent
	(*Span)(nil),           // 3: greplog.v1.Span
	(*Metric)(nil),         // 4: greplog.v1.Metric
	(*IngestBatch)(nil),    // 5: greplog.v1.IngestBatch
	(*IngestResponse)(nil), // 6: greplog.v1.IngestResponse
	nil,                    // 7: greplog.v1.LogEvent.AttributesEntry
	nil,                    // 8: greplog.v1.Span.AttributesEntry
	nil,                    // 9: greplog.v1.Metric.LabelsEntry
}
var file_greplog_v1_events_proto_depIdxs = []int32{
	7, // 0: greplog.v1.LogEvent.attributes:type_name -> greplog.v1.LogEvent.AttributesEntry
	8, // 1: greplog.v1.Span.attributes:type_name -> greplog.v1.Span.AttributesEntry
	0, // 2: greplog.v1.Span.kind:type_name -> greplog.v1.SpanKind
	9, // 3: greplog.v1.Metric.labels:type_name -> greplog.v1.Metric.LabelsEntry
	1, // 4: greplog.v1.Metric.type:type_name -> greplog.v1.MetricType
	2, // 5: greplog.v1.IngestBatch.logs:type_name -> greplog.v1.LogEvent
	3, // 6: greplog.v1.IngestBatch.spans:type_name -> greplog.v1.Span
	4, // 7: greplog.v1.IngestBatch.metrics:type_name -> greplog.v1.Metric
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_greplog_v1_events_proto_init() }
func file_greplog_v1_events_proto_init() {
	if File_greplog_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greplog_v1_events_proto_rawDesc), len(file_greplog_v1_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_greplog_v1_events_proto_goTypes,
		DependencyIndexes: file_greplog_v1_events_proto_depIdxs,
		EnumInfos:         file_greplog_v1_events_proto_enumTypes,
		MessageInfos:      file_greplog_v1_events_proto_msgTypes,
	}.Build()
	File_greplog_v1_events_proto = out.File
	file_greplog_v1_events_proto_goTypes = nil
	file_greplog_v1_events_proto_depIdxs = nil
}
